/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as IndexRouteImport } from './routes/index'

const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/navigation': typeof NavigationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/navigation': typeof NavigationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/navigation': typeof NavigationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/navigation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/navigation'
  id: '__root__' | '/' | '/navigation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NavigationRoute: typeof NavigationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NavigationRoute: NavigationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
